services:
  db:
    image: mysql:8.0
    container_name: mysql-env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  webapp:
    image: nginx
    container_name: webapp-env
    ports:
      - "8081:80"
    volumes:
      - ./app:/usr/share/nginx/html

volumes:
  db_data:
