# Use a lightweight base image
FROM alpine:latest

# Add a label (metadata)
LABEL maintainer="karljoshuaencio@github"

# Run a command when building
RUN echo "Building my first Dockerfile image!"

# Default command when container starts
CMD ["echo", "Hello from my first Dockerfile!"]
