version: "3.8"

services:
  app:
    image: php:8.2-cli
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
